### ISSUE TITLE
make examples fully self-contained by loading data from the web

### ISSUE THREAD

**Issue by nicholasjhorton** [mine-cetinkaya-rundel/reproducibility-uscots15#1]
Can the various read.csv() calls be replaced with URL's to allow remote access?

ex1-template.Rmd:gap_5060 = read.csv("data/gapminder-5060.csv")
ex2-template.Rmd:gap_7080 <- read.csv('data/gapminder-7080.csv')
ex2-template.Rmd:gap_90plus <- read.csv('data/gapminder-90plus.csv')

**Comment by mine-cetinkaya-rundel** [comment]
yup, done!
